project_id = "oodqharaqstrbfoqjgfh"

[functions.create-payment]
verify_jwt = false

[functions.confirm-upload]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.admin-verify]
verify_jwt = false

[functions.admin-delete-upload]
verify_jwt = false

[functions.admin-update-pricing]
verify_jwt = false