// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oodqharaqstrbfoqjgfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vZHFoYXJhcXN0cmJmb3FqZ2ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTQ4MzgsImV4cCI6MjA2OTEzMDgzOH0.LioBvZCb4FxXPQDm--tXZcsF4dDAWiq7IpbtGabJYVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});